### ISSUE TITLE
Add MySQL toggle and functionality to Dictionary Creator GUI

### ISSUE THREAD

**Issue by MatthewVi** [GoTeamEpsilon/ctakes-rest-service#2]

**Comment by MatthewVita** [comment]
@gandhirajan I got started on this. Basically I'm finding that `ctakes-gui` is the project in cTAKES that holds this code. It appears that the `custom-dictionary-name-here.script` is actually not generated by Java, but HSQLDB. It's pretty much a "dump" of the created HSQLDB.

I'm going to create the base schema with MySQL (already have this done really), sneak a JDBC MySQL connection in the code (reads from an xml configuration file), add a UI toggle, write data to either MySQL or HSQLDB.

**Comment by gandhirajan** [comment]
@MatthewVita  Have not looked at the code yet. But the approach looks fine Do let me know if you need any help on this.

**Comment by MatthewVita** [comment]
@gandhirajan @ShaneChesnutt Just a small update that I'm very comfortable with the code now that I've studied it. Currently creating `org.apache.ctakes.gui.dictionary.util.MysqlUtil` class and will get it working and then update the GUI :)

**Comment by MatthewVita** [comment]
Ugh `14 Dec 2017 22:01:02 ERROR JdbcUtil - Could not register Driver com.mysql.jdbc.driver
14 Dec 2017 22:01:02 ERROR JdbcUtil - com.mysql.jdbc.driver`

Trying my best to get around this :)

**Comment by gandhirajan** [comment]
I jus had a look at it. Looks like ctakes-gui module dont have mysql dependency mentioned in pom.xml

Add the following in ctakes-gui's pom.xml and you should be good to go:
<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<version>6.0.6</version>
		</dependency>

**Comment by MatthewVita** [comment]
No luck! I tried that last night:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
   <modelVersion>4.0.0</modelVersion>
   <parent>
      <groupId>org.apache.ctakes</groupId>
      <artifactId>ctakes</artifactId>
      <version>4.0.1-SNAPSHOT</version>
   </parent>

   <artifactId>ctakes-gui</artifactId>
   <name>ctakes-gui</name>
   <description>module with gui components and simple run tools</description>

   <dependencies>
      <dependency>
         <groupId>org.apache.ctakes</groupId>
         <artifactId>ctakes-gui-res</artifactId>
      </dependency>
      <dependency>
         <groupId>org.apache.ctakes</groupId>
         <artifactId>ctakes-core</artifactId>
      </dependency>
      <dependency>
         <groupId>org.hsqldb</groupId>
         <artifactId>hsqldb</artifactId>
         <version>2.3.4</version>
      </dependency>
      <dependency>
         <groupId>mysql</groupId>
         <artifactId>mysql-connector-java</artifactId>
         <version>6.0.6</version>
     </dependency>
     <dependency>
         <groupId>log4j</groupId>
         <artifactId>log4j</artifactId>
      </dependency>
      <dependency>
         <groupId>junit</groupId>
         <artifactId>junit</artifactId>
      </dependency>
      <dependency>
         <groupId>io.github.lukehutch</groupId>
         <artifactId>fast-classpath-scanner</artifactId>
         <version>2.0.18</version>
      </dependency>
   </dependencies>

</project>
```

**Comment by gandhirajan** [comment]
Could you load the module code changes on git so that I can have a look at the issue by simulating the same in my local setup?

**Comment by MatthewVita** [comment]
Ah HA! I found out the source of the issue. This one definitely took me a while and was super subtle!

If you visit `/ctakes/ctakes-distribution/src/main/assembly/bin.xml`,   `<exclude>mysql:*</exclude>` is present because it's `non-asf compliant dependencies used by ytex`.

I'm going to see if there's a way we can use MySQL in cTAKES in a way that is compliant with ASF. I wonder if MariaDB or Postgresql would be better because they work with JDBC and are free/open source.

@gandhirajan

**Comment by MatthewVi** [comment]
Sticking with hsqldb for now
