### ISSUE TITLE
Next steps with the Spring Upgrade in place

### ISSUE THREAD

**Issue by MatthewVita** [GoTeamEpsilon/ctakes-rest-service#23]
@gandhirajan,

Thanks to your wonderful work on getting Spring updated in the core codebase, we can discuss what can be deleted from this codebase in terms of the copied Java files. 

I am guessing we will be able to rid of the poms but may need to keep the code that alters the JDBC to work with MySQL? (I.E.: Switching out SimpleJdbcTemplate)

Thank you for being patient with me being on my trip. I realize I haven't been fast with my responses.

**Comment by gandhirajan** [comment]
Hi Matt, as you mentioned we need to do some modifications to the pom. Also we need to get rid of repo folder as well. But only prob in getting rid of it is to figure out a way to pass custom XML as suggested by Sean. We will be checking on this. Also we need to make changes in Pipeline.java to remove hardcoded pipelines and read it from piper config file. This will next course of action for me and Sandeep. Planning to create a new module called "ctakes-web-rest" here and proceed. We will keep you posted.
