### ISSUE TITLE
CTAKES Rest Service API throws error

### ISSUE THREAD

**Issue by LeninChristopher** [GoTeamEpsilon/ctakes-rest-service#24]
Hi @gandhirajan ,

On using maven packaging with 'ctakes-rest-service' throws error..is there any documentation available

D:\cTakes\ctakes-rest-service-master\ctakes-rest-service>mvn package
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building ctakes-nlp-service 4.0.1
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.apache.ctakes:ctakes-type-system:jar:4.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.ctakes:ctakes-utils:jar:4.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.ctakes:ctakes-core:jar:4.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.ctakes:ctakes-core-res:jar:4.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.ctakes:ctakes-dictionary-lookup:jar:4.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.ctakes:ctakes-dictionary-lookup-res:jar:4.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.ctakes:ctakes-dictionary-lookup-fast:jar:4.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.ctakes:ctakes-dictionary-lookup-fast-res:jar:4.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.ctakes:ctakes-preprocessor:jar:4.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.ctakes:ctakes-pos-tagger:jar:4.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.ctakes:ctakes-pos-tagger-res:jar:4.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.ctakes:ctakes-chunker:jar:4.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.ctakes:ctakes-chunker-res:jar:4.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.ctakes:ctakes-lvg:jar:4.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.ctakes:ctakes-lvg-res:jar:4.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.ctakes:ctakes-context-tokenizer:jar:4.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.ctakes:ctakes-clinical-pipeline:jar:4.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.ctakes:ctakes-clinical-pipeline-res:jar:4.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.ctakes:ctakes-ne-contexts:jar:4.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.ctakes:ctakes-ne-contexts-res:jar:4.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.ctakes:ctakes-assertion:jar:4.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.ctakes:ctakes-assertion-res:jar:4.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.ctakes:ctakes-assertion-zoner:jar:4.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.ctakes:ctakes-assertion-zoner-res:jar:4.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.ctakes:ctakes-constituency-parser:jar:4.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.ctakes:ctakes-constituency-parser-res:jar:4.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.ctakes:ctakes-coreference:jar:4.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.ctakes:ctakes-coreference-res:jar:4.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.ctakes:ctakes-drug-ner:jar:4.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.ctakes:ctakes-drug-ner-res:jar:4.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.ctakes:ctakes-side-effect:jar:4.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.ctakes:ctakes-side-effect-res:jar:4.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.ctakes:ctakes-smoking-status:jar:4.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.ctakes:ctakes-smoking-status-res:jar:4.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.ctakes:ctakes-dependency-parser:jar:4.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.ctakes:ctakes-dependency-parser-res:jar:4.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.ctakes:ctakes-relation-extractor:jar:4.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.ctakes:ctakes-relation-extractor-res:jar:4.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.ctakes:ctakes-temporal:jar:4.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.ctakes:ctakes-temporal-res:jar:4.0.1-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.146 s
[INFO] Finished at: 2017-12-06T12:51:00+05:30
[INFO] Final Memory: 7M/155M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project ctakes-nlp-service: Could not resolve dependencies for project org.apache.ctakes:ctakes-nlp-service:war:4.0.1: The following artifacts could not be resolved: org.apache.ctakes:ctakes-type-system:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-utils:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-core:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-core-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-dictionary-lookup:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-dictionary-lookup-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-dictionary-lookup-fast:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-dictionary-lookup-fast-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-preprocessor:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-pos-tagger:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-pos-tagger-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-chunker:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-chunker-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-lvg:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-lvg-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-context-tokenizer:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-clinical-pipeline:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-clinical-pipeline-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-ne-contexts:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-ne-contexts-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-assertion:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-assertion-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-assertion-zoner:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-assertion-zoner-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-constituency-parser:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-constituency-parser-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-coreference:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-coreference-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-drug-ner:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-drug-ner-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-side-effect:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-side-effect-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-smoking-status:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-smoking-status-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-dependency-parser:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-dependency-parser-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-relation-extractor:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-relation-extractor-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-temporal:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-temporal-res:jar:4.0.1-SNAPSHOT: Failure to find org.apache.ctakes:ctakes-type-system:jar:4.0.1-SNAPSHOT in file://D:\cTakes\ctakes-rest-service-master\ctakes-rest-service/repo was cached in the local repository, resolution will not be reattempted until the update interval of localrepository has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by gandhirajan** [comment]
This module is kind of obsolete now. You may have to look at this - https://github.com/GoTeamEpsilon/ctakes-rest-service/tree/master/ctakes-web-rest

**Comment by MatthewVita** [comment]
@LeninChristopher Hope you find the new solution that @gandhirajan posted to be helpful. Please do note that this solution is "alpha" but we are making progress now that our team is forming (@gandhirajan has been amazingly patient while others join in).

Please consider joining our efforts!
