### ISSUE TITLE
ctakes-rest-service on Windows 10 - ERROR: Service 'ctakes_webserver' failed to build

### ISSUE THREAD

**Issue by Artgit** [GoTeamEpsilon/ctakes-rest-service#28]
First of all, I'd like to thank you for your work! 

I try to run this ctakes-rest-service on my Windows 10 machine:

docker-compose up
```
Building ctakes_webserver
Step 1/5 : FROM tomcat:8.0
 ---> e0919ffed768
Step 2/5 : COPY . .
 ---> Using cache
 ---> af942ac032b3
Step 3/5 : ADD install.sh ./install.sh
 ---> Using cache
 ---> 3bfaf03514a2
Step 4/5 : RUN chmod +x ./install.sh
 ---> Using cache
 ---> 0f2ed44f0187
Step 5/5 : RUN ./install.sh
 ---> Running in e9bfb1368eac
/bin/sh: 1: ./install.sh: not found
ERROR: Service 'ctakes_webserver' failed to build: The command '/bin/sh -c ./install.sh' returned a non-zero code: 127
```

as you may see it is fail with the following:

> ERROR: Service 'ctakes_webserver' failed to build: The command '/bin/sh -c ./install.sh' returned a non-zero code: 127

what I'm doing wrong and how to fix it ? Thanks !

**Comment by MatthewVita** [comment]
Please do note that this solution is "alpha" (the Docker code is barely even alpha) but we are making progress now that our team is forming.

Please consider joining our efforts!
