### ISSUE TITLE
help needed ctakes-web-rest build failed

### ISSUE THREAD

**Issue by swagat123** [GoTeamEpsilon/ctakes-rest-service#35]
Hi All

i clone this repository and try to run this ctakes-web-rest.added the umls credential inside dictionary . try to build the maven package but it throws error.

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.871 s
[INFO] Finished at: 2018-07-26T23:44:31+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project ctakes-web-rest: Could not resolve dependencies for project org.apache.ctakes:ctakes-web-rest:war:4.0.1: The following artifacts could not be resolved: org.apache.ctakes:ctakes-type-system:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-utils:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-core:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-core-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-dictionary-lookup:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-dictionary-lookup-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-dictionary-lookup-fast:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-dictionary-lookup-fast-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-preprocessor:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-pos-tagger:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-pos-tagger-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-chunker:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-chunker-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-lvg:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-lvg-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-context-tokenizer:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-clinical-pipeline:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-clinical-pipeline-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-ne-contexts:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-ne-contexts-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-assertion:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-assertion-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-assertion-zoner:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-assertion-zoner-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-constituency-parser:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-constituency-parser-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-coreference:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-coreference-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-drug-ner:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-drug-ner-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-side-effect:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-side-effect-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-smoking-status:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-smoking-status-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-dependency-parser:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-dependency-parser-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-relation-extractor:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-relation-extractor-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-temporal:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-temporal-res:jar:4.0.1-SNAPSHOT: Could not find artifact org.apache.ctakes:ctakes-type-system:jar:4.0.1-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

is there any other settings/configs needs to be done which i am missing.

Thanks
Swagat

**Comment by swagat123** [comment]
@gandhirajan 

I have chekout the code from eclipse using the link(https://svn.apache.org/repos/asf/ctakes/branches/ctakes-4.0.0/). Then copied the files from SpringUpgrade  to catkes core ,after that try to build the ctakes core  using clean install. I faced the below error

[INFO] Scanning for projects...
[ERROR] [ERROR] The projects in the reactor contain a cyclic reference: Edge between 'Vertex{label='org.apache.ctakes:ctakes-ytex:4.0.1-SNAPSHOT'}' and 'Vertex{label='org.apache.ctakes:ctakes-clinical-pipeline:4.0.1-SNAPSHOT'}' introduces to cycle in the graph org.apache.ctakes:ctakes-clinical-pipeline:4.0.1-SNAPSHOT --> org.apache.ctakes:ctakes-ytex:4.0.1-SNAPSHOT --> org.apache.ctakes:ctakes-clinical-pipeline:4.0.1-SNAPSHOT @ 
[ERROR] The projects in the reactor contain a cyclic reference: Edge between 'Vertex{label='org.apache.ctakes:ctakes-ytex:4.0.1-SNAPSHOT'}' and 'Vertex{label='org.apache.ctakes:ctakes-clinical-pipeline:4.0.1-SNAPSHOT'}' introduces to cycle in the graph org.apache.ctakes:ctakes-clinical-pipeline:4.0.1-SNAPSHOT --> org.apache.ctakes:ctakes-ytex:4.0.1-SNAPSHOT --> org.apache.ctakes:ctakes-clinical-pipeline:4.0.1-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectCycleException

I appreciate your suggestions.

Regards
Swagat

**Comment by MatthewVita** [comment]
Hi. One of the Team Epsilon folks here. I have been away from open source for many months due to health issues.

You may be interested in reviewing the brand new README, which may lead you to a smoother install. Please let me know if you have any difficulties navigating it.
