### ISSUE TITLE
Perform custom dictionary testing

### ISSUE THREAD

**Issue by MatthewVi** [GoTeamEpsilon/ctakes-rest-service#4]

**Comment by MatthewVita** [comment]
@gandhirajan  I'm getting the MySQL-capable dictionary creator stuff ready. I generated a dictionary and then made sure the cTAKES configuration points at it. However, when I deploy our war, I get a 404 on the POST endpoint :confused:
I'll have to do more testing, but this was my result from a quick test yesterday

**Comment by gandhirajan** [comment]
@matthewvita, did u had a chance to look at the latest ctakes web rest module readme, the endpoint URL has changed a bit.please email the error screenshot

**Comment by MatthewVita** [comment]
@gandhirajan will look into that!

**Comment by MatthewVi** [comment]
Sticking with hsqldb for now
