### ISSUE TITLE
Out of memory errors when querying API

### ISSUE THREAD

**Issue by tjaffri** [GoTeamEpsilon/ctakes-rest-service#47]
I am not able to query the API after setting up. Specifically:

Querying http://localhost:8080/ctakes-web-rest/index.jsp returns valid HTML (I believe the index page). So the tomcat setup seems valid.

Issuing a POST to http://localhost:8080/ctakes-web-rest/service/analyze?pipeline=Default returns a 500 error. Investigating catalina.out shows a Java Heap OutOfMemory error, which seems strange since I am posting only a very small file (5 lines of medical jargon).

I am on an ubuntu 18 ec2 instance. Pretty beefy p2.xlarge (I believe it has 64GB RAM). Should not be running out of memory, so not sure what's going on. Any ideas?

**Comment by MatthewVi** [comment]
@tjaffri Haven't seen this - doesn't sound pleasant. Can you paste the complete stack trace?

**Comment by tjaffri** [comment]
Here is some more information:

## System
```bash
(base) ubuntu@ip-172-31-38-215:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
## Hardware
```bash
(base) ubuntu@ip-172-31-38-215:~$ sudo lshw -short
H/W path    Device   Class      Description
===========================================
                     system     HVM domU
/0                   bus        Motherboard
/0/0                 memory     96KiB BIOS
/0/401               processor  Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
/0/402               processor  CPU
/0/403               processor  CPU
/0/404               processor  CPU
/0/1000              memory     61GiB System Memory
/0/1000/0            memory     16GiB DIMM RAM
/0/1000/1            memory     16GiB DIMM RAM
/0/1000/2            memory     16GiB DIMM RAM
/0/1000/3            memory     13GiB DIMM RAM
/0/100               bridge     440FX - 82441FX PMC [Natoma]
/0/100/1             bridge     82371SB PIIX3 ISA [Natoma/Triton II]
/0/100/1.1           storage    82371SB PIIX3 IDE [Natoma/Triton II]
/0/100/1.3           bridge     82371AB/EB/MB PIIX4 ACPI
/0/100/2             display    GD 5446
/0/100/3    ens3     network    Ethernet interface
/0/100/1e            display    GK210GL [Tesla K80]
/0/100/1f            generic    Xen Platform Device
/1          docker0  network    Ethernet interface
```
## Java
```bash
(base) ubuntu@ip-172-31-38-215:~$ java -version
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (Zulu 8.20.0.5-linux64) (build 1.8.0_121-b15)
OpenJDK 64-Bit Server VM (Zulu 8.20.0.5-linux64) (build 25.121-b15, mixed mode)
```

## Querying API Index Page
```bash
(base) ubuntu@ip-172-31-38-215:~$ wget http://localhost:8080/ctakes-web-rest/index.jsp 
--2018-10-06 20:17:52--  http://localhost:8080/ctakes-web-rest/index.jsp
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:8080... connected.
HTTP request sent, awaiting response... 200 
Length: 753 [text/html]
Saving to: ‘index.jsp’

index.jsp                 100%[===================================>]     753  --.-KB/s    in 0s      

2018-10-06 20:17:52 (107 MB/s) - ‘index.jsp’ saved [753/753]

(base) ubuntu@ip-172-31-38-215:~$ more index.jsp 
<!DOCTYPE html>

<html>
    <head>
        <link rel="stylesheet" type="text/css" href="css/index.css">
        <title> Ctakes Rest Service Test </title>
		<script type="text/javascript" src="js/jquery.js"></script>			
		<script type="text/javascript" src="js/app.js"></script>
        <script>var myContextPath = "/ctakes-web-rest"</script>
    </head>
    <body>
        <img src="http://ctakes.apache.org/images/ctakes_logo.jpg"/>
        <br>Version: 4.0.1</br>
		</br>
        <h3>cTAKES REST SERVICE TESTING</h3>		
        <textarea id="analysisText" name="analysisText" rows="6" cols="75" onFocus="this.value=''">Ent
er your text for analysis</textarea><br>
        <input type="button" value="Analyze" name="fire" id="fire"/>
    </body>
</html>
```

## Querying API With Data
```bash
(base) ubuntu@ip-172-31-38-215:~/Source/github/ctakes-rest-service/test_data$ curl -X POST -H "Content-Type: text/plain" --data "Hello World" http://localhost:8080/ctakes-web-rest/service/analyze?pipeline=Default
<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1><hr class="line" /><p><b>Type</b> Exception Report</p><p><b>Message</b> Servlet.init() for servlet [ctakes-rest-service] threw exception</p><p><b>Description</b> The server encountered an unexpected condition that prevented it from fulfilling the request.</p><p><b>Exception</b></p><pre>javax.servlet.ServletException: Servlet.init() for servlet [ctakes-rest-service] threw exception
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	java.base&#47;java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	java.base&#47;java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.base&#47;java.lang.Thread.run(Thread.java:844)
</pre><p><b>Root Cause</b></p><pre>org.springframework.beans.factory.BeanCreationException: Error creating bean with name &#39;ctakesRestController&#39;: Invocation of init method failed; nested exception is java.lang.OutOfMemoryError: Java heap space
	org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:137)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:409)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1620)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:668)
	org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:634)
	org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:682)
	org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:553)
	org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:494)
	org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:171)
	javax.servlet.GenericServlet.init(GenericServlet.java:158)
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	java.base&#47;java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	java.base&#47;java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.base&#47;java.lang.Thread.run(Thread.java:844)
</pre><p><b>Root Cause</b></p><pre>java.lang.OutOfMemoryError: Java heap space
	com.googlecode.clearnlp.classification.model.AbstractModel.loadWeightVector(AbstractModel.java:354)
	com.googlecode.clearnlp.classification.model.StringModel.load(StringModel.java:80)
	com.googlecode.clearnlp.classification.model.AbstractModel.&lt;init&gt;(AbstractModel.java:80)
	com.googlecode.clearnlp.classification.model.StringModel.&lt;init&gt;(StringModel.java:65)
	com.googlecode.clearnlp.component.AbstractStatisticalComponent.loadStatisticalModels(AbstractStatisticalComponent.java:154)
	com.googlecode.clearnlp.component.dep.CDEPPassParser.loadModels(CDEPPassParser.java:145)
	com.googlecode.clearnlp.component.AbstractStatisticalComponent.&lt;init&gt;(AbstractStatisticalComponent.java:93)
	com.googlecode.clearnlp.component.dep.CDEPPassParser.&lt;init&gt;(CDEPPassParser.java:108)
	com.googlecode.clearnlp.engine.EngineGetter.getComponent(EngineGetter.java:248)
	org.apache.ctakes.dependency.parser.ae.shared.DependencySharedModel.getModel(DependencySharedModel.java:52)
	org.apache.ctakes.dependency.parser.ae.shared.DependencySharedModel.load(DependencySharedModel.java:39)
	org.apache.uima.resource.impl.ResourceManager_impl.registerResource(ResourceManager_impl.java:603)
	org.apache.uima.resource.impl.ResourceManager_impl.initializeExternalResources(ResourceManager_impl.java:442)
	org.apache.uima.resource.Resource_ImplBase.initialize(Resource_ImplBase.java:153)
	org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.initialize(AnalysisEngineImplBase.java:157)
	org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initialize(PrimitiveAnalysisEngine_impl.java:123)
	org.apache.uima.impl.AnalysisEngineFactory_impl.produceResource(AnalysisEngineFactory_impl.java:94)
	org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)
	org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:269)
	org.apache.uima.UIMAFramework.produceAnalysisEngine(UIMAFramework.java:387)
	org.apache.uima.analysis_engine.asb.impl.ASB_impl.setup(ASB_impl.java:254)
	org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initASB(AggregateAnalysisEngine_impl.java:431)
	org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initializeAggregateAnalysisEngine(AggregateAnalysisEngine_impl.java:375)
	org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initialize(AggregateAnalysisEngine_impl.java:185)
	org.apache.uima.impl.AnalysisEngineFactory_impl.produceResource(AnalysisEngineFactory_impl.java:94)
	org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)
	org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:269)
	org.apache.uima.UIMAFramework.produceAnalysisEngine(UIMAFramework.java:354)
	org.apache.ctakes.rest.service.CtakesRestController$PipelineRunner.&lt;init&gt;(CtakesRestController.java:100)
	org.apache.ctakes.rest.service.CtakesRestController$PipelineRunner.&lt;init&gt;(CtakesRestController.java:91)
	org.apache.ctakes.rest.service.CtakesRestController.init(CtakesRestController.java:62)
	java.base&#47;jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
</pre><p><b>Note</b> The full stack trace of the root cause is available in the server logs.</p><hr class="line" /><h3>Apache Tomcat/8.5.34</h3></body></html>
```

**Comment by tjaffri** [comment]
One note: I am not using the form on the index.jsp to post... since I am SSH connected to my instance and the localhost URL is not available externally form a browser. I don't think that should make any difference, but maybe I am doing my POST in a different format than you are? Hopefully the stack trace tells you something more than it is telling me... looks like out of heap space Out of Memory... but that should not happen on this machine, there is about 13 GB of Java heap space.

**Comment by ultragen74** [comment]
47 Out of memory errors when querying API 


<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}.line {height: 1px; background-color: #525D76; border: none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1><hr class="line" /><p><b>Type</b> Exception Report</p><p><b>Message</b> Servlet.init() for servlet ctakes-rest-service threw exception</p><p><b>Description</b> The server encountered an unexpected condition that prevented it from fulfilling the request.</p><p><b>Exception</b></p><pre>javax.servlet.ServletException: Servlet.init() for servlet ctakes-rest-service threw exception
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:492)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
	org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1152)
	org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1539)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1495)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.lang.Thread.run(Thread.java:748)
</pre><p><b>Root Cause</b></p><pre>org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ctakesRestController': Invocation of init method failed; nested exception is java.lang.OutOfMemoryError: Java heap space
	org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:137)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:409)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1620)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:668)
	org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:634)
	org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:682)
	org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:553)
	org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:494)
	org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:171)
	javax.servlet.GenericServlet.init(GenericServlet.java:158)
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:492)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
	org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1152)
	org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1539)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1495)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.lang.Thread.run(Thread.java:748)
</pre><p><b>Root Cause</b></p><pre>java.lang.OutOfMemoryError: Java heap space
</pre><p><b>Note</b> The full stack trace of the root cause is available in the server logs.</p><hr class="line" /><h3>Apache Tomcat/8.0.53</h3></body></html>

**Comment by MatthewVi** [comment]
Hi @tjaffri and @ultragen74,

Sorry for the delayed response. I am not getting these errors on Ubuntu and Mac.

My only thought is to increase the JVM heap size: https://stackoverflow.com/questions/10003459/java-opts-for-increasing-heap-size

cc: @gandhirajan any thoughts on this?

**Comment by ultragen74** [comment]
hi, @MatthewVi I am also using Ubuntu  18.04  with low RAM capacity of 3 GB on Digital Ocean.

Can increasing RAM size will solve my problem?

**Comment by gandhirajan** [comment]
@ultragen74, it requires 4gb memory to run ctakes in tomcat server as it has to load lot of objects for processing. So as @MatthewVi mentioned you gotta increase the server heap space to resolve this.

**Comment by ultragen74** [comment]
Thanks @MatthewVi

**Comment by ultragen74** [comment]
intx CompilerThreadStackSize                   = 0                                   {pd product}
    uintx ErgoHeapSizeLimit                         = 0                                   {product}
    uintx HeapSizePerGCThread                       = 87241520                            {product}
    uintx InitialHeapSize                          := 536870912                           {product}
    uintx LargePageHeapSizeThreshold                = 134217728                           {product}
    uintx MaxHeapSize                              := 3223322624                         {product}
     intx ThreadStackSize                          := 512                                 {pd product}
     intx VMThreadStackSize                         = 1024                                {pd product}


Still the same output java.lang.OutOfMemoryError: Java heap space

**Comment by ultragen74** [comment]
MemTotal:        4039592 kB
MemFree:         2124328 kB
MemAvailable:    2308472 kB
Buffers:           23352 kB
Cached:           353652 kB
SwapCached:            0 kB
Active:          1676684 kB
Inactive:         138028 kB
Active(anon):    1442144 kB
Inactive(anon):      212 kB
Active(file):     234540 kB
Inactive(file):   137816 kB
Unevictable:        5408 kB
Mlocked:            5408 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:                16 kB
Writeback:             0 kB
AnonPages:       1443116 kB
Mapped:            75416 kB
Shmem:               612 kB
Slab:              57560 kB
SReclaimable:      29828 kB
SUnreclaim:        27732 kB
KernelStack:        3408 kB
PageTables:         9980 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     2019796 kB
Committed_AS:    2062864 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:       77804 kB
DirectMap2M:     3067904 kB
DirectMap1G:     1048576 kB

**Comment by gandhirajan** [comment]
@ultragen74  I feel your memory settings are not getting picked by the server. Can you share your heap settings? Also are you using 32 bit or 64 bit JDK?

**Comment by ultragen74** [comment]
@gandhirajan  Thanks and its Done!

**Comment by tjaffri** [comment]
Thanks. I'm going to try this tonight and see if increasing heap space helps... @ultragen74  could you perhaps help me by documenting exactly what you did to increase heap space?

**Comment by fakabbir** [comment]
> One note: I am not using the form on the index.jsp to post... since I am SSH connected to my instance and the localhost URL is not available externally from a browser. I don't think that should make any difference, but maybe I am doing my POST in a different format than you are (the ajax code doing the form post seems to me to be doing the same thing as my curl command)?
> 
> Hopefully the stack trace tells you something more than it is telling me... looks like out of heap space Out of Memory... but that should not happen on this machine, there is about 13 GB of Java heap space.
> 
> ```shell
> (base) ubuntu@ip-172-31-38-215:~/Source/github/ctakes-rest-service/test_data$ java -XshowSettings:vm
> VM settings:
>     Max. Heap Size (Estimated): 13.32G
>     Ergonomics Machine Class: server
>     Using VM: OpenJDK 64-Bit Server VM
> ```

- You can use browser to run ctakes uafter opening 8080 port
![image](https://user-images.githubusercontent.com/13721550/47539111-44072300-d8ec-11e8-9e47-63e458484cb9.png)

- Edit and add 8080 under custom TCP
![image](https://user-images.githubusercontent.com/13721550/47539132-6305b500-d8ec-11e8-86cd-d8f73d623947.png)

I'm also facing the same issue with Java Heap Memory Out of Space. This isn't an issue with cTakes or VM but instead with the default memory allocated to java. 

I'was using AWS free tier VM which has 1GB of RAM and `java -Xms512m -Xmx1024m`  didn't worked for that.

**Comment by subuiyer411** [comment]
> @gandhirajan Thanks and its Done!

@ultragen74 I'm facing the same issue, could you please elaborate on the fix you used

**Comment by tjaffri** [comment]
Hi everyone... see PR #51. I included some instructions on how to get past this error. Will close this issue once that PR is merged.

**Comment by laratutoteam** [comment]
**get this easy error solving** https://laratuto.com/solved-out-of-memory-error-in-query-sybase_connect/
