### ISSUE TITLE
Maven Error

### ISSUE THREAD

**Issue by subuiyer411** [GoTeamEpsilon/ctakes-rest-service#48]
Getting an error on step 7 line 2 (mvn install -Dmaven.test.skip=true). Have included the logs below. Not a core Java/Maven user. Any help would be appreciated.

<pre>[<font color="#729FCF"><b>INFO</b></font>] Scanning for projects...
[<font color="#729FCF"><b>INFO</b></font>] 
[<font color="#729FCF"><b>INFO</b></font>] <b>------------------------------------------------------------------------</b>
[<font color="#729FCF"><b>INFO</b></font>] <b>Building Apache cTAKES Distribution 4.0.1-SNAPSHOT</b>
[<font color="#729FCF"><b>INFO</b></font>] <b>------------------------------------------------------------------------</b>
[<font color="#FCE94F"><b>WARNING</b></font>] The POM for org.glassfish:javax.el:jar:3.0.1-b06-SNAPSHOT is missing, no dependency information available
[<font color="#FCE94F"><b>WARNING</b></font>] The POM for org.glassfish:javax.el:jar:3.0.1-b07-SNAPSHOT is missing, no dependency information available
[<font color="#FCE94F"><b>WARNING</b></font>] The POM for org.glassfish:javax.el:jar:3.0.1-b08-SNAPSHOT is missing, no dependency information available
[<font color="#729FCF"><b>INFO</b></font>] 
[<font color="#729FCF"><b>INFO</b></font>] <b>--- </b><font color="#4E9A06">maven-remote-resources-plugin:1.4:process</font> <b>(default)</b> @ <font color="#06989A">ctakes-distribution</font><b> ---</b>
[<font color="#729FCF"><b>INFO</b></font>] <b>------------------------------------------------------------------------</b>
[<font color="#729FCF"><b>INFO</b></font>] <font color="#EF2929"><b>BUILD FAILURE</b></font>
[<font color="#729FCF"><b>INFO</b></font>] <b>------------------------------------------------------------------------</b>
[<font color="#729FCF"><b>INFO</b></font>] Total time: 17.307 s
[<font color="#729FCF"><b>INFO</b></font>] Finished at: 2018-10-30T19:50:23+05:30
[<font color="#729FCF"><b>INFO</b></font>] Final Memory: 25M/230M
[<font color="#729FCF"><b>INFO</b></font>] <b>------------------------------------------------------------------------</b>
[<font color="#EF2929"><b>ERROR</b></font>] Failed to execute goal <font color="#4E9A06">org.apache.maven.plugins:maven-remote-resources-plugin:1.4:process</font> <b>(default)</b> on project <font color="#06989A">ctakes-distribution</font>: <font color="#EF2929"><b>Error finding remote resources manifests</b></font>: /home/subu/Downloads/ctakes-rest-service/ctakes-codebase-area/trunk/ctakes-distribution/target/maven-shared-archive-resources/META-INF/NOTICE (No such file or directory) -&gt; <b>[Help 1]</b>
[<font color="#EF2929"><b>ERROR</b></font>] 
[<font color="#EF2929"><b>ERROR</b></font>] To see the full stack trace of the errors, re-run Maven with the <b>-e</b> switch.
[<font color="#EF2929"><b>ERROR</b></font>] Re-run Maven using the <b>-X</b> switch to enable full debug logging.
[<font color="#EF2929"><b>ERROR</b></font>] 
[<font color="#EF2929"><b>ERROR</b></font>] For more information about the errors and possible solutions, please read the following articles:
[<font color="#EF2929"><b>ERROR</b></font>] <b>[Help 1]</b> http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
</pre>

**Comment by carlosarranz7** [comment]
I have the same issue, did you fixed it?

**Comment by subuiyer411** [comment]
@carlosarranz7  Yes, got CTakes working. Multiple fixes were needed to get it fully working. Do follow @tjaffri [instructions ](https://github.com/GoTeamEpsilon/ctakes-rest-service/commits/master/README.md?author=tjaffri) on increasing memory heap space.  MySQL also needs certain changes such as changing the root password to pass and changing the table names to uppercase. These should help, if not we can discuss further.
