### ISSUE TITLE
TimeMention tag is not working

### ISSUE THREAD

**Issue by balavenkatesh3322** [GoTeamEpsilon/ctakes-rest-service#50]
Temporal expression part is not working. I send an input as **I had a back pain for four days ago** which is not identified. It should identify this (**for four days ago**) word from the input  

@MatthewVita Please check the issue as soon as possible.

FYI: [https://cwiki.apache.org/confluence/display/CTAKES/cTAKES+4.0+-+Temporal+Module]()

**Comment by tjaffri** [comment]
Hi, @balavenkatesh3322 ... I see the same issue. May I ask why you closed this? Were you able to get time mention tags working somehow? Can you please share a sample string for which the tags work?
