### ISSUE TITLE
When running in web server, does it use "resources" folder from "ctakes-rest-service/ctakes-web-rest/src/main/" or from the SVN branch we download it from?

### ISSUE THREAD

**Issue by legendactivated** [GoTeamEpsilon/ctakes-rest-service#57]
Hello @MatthewVita @gandhirajan 

Sorry to log it as an "issue"...... this is more of a question. 

First of all, thank you for putting this together. It is so much helpful. I can get everything up and running with simple instructions listed on the intro page!

The reason I am asking above question is because I was looking at "Temporal module" and what it should give back and I saw some discrepancy.

Discrepancy I noticed is that I see TemporalSubPipe.piper file referencing "/org/apache/ctakes/temporal/ae/eventtime/model.jar" jar file. However, in "resources" folder in this Git repo, the path is actually "/org/apache/ctakes/temporal/ae/eventtime/20150629/model.jar"....notice the "20150629" date.

So, I wanted to know whether this is an issue or does Ctakes actually uses this model.jar from ctakes-temporal-res module >> resources folder?

If this is a stupid question, feel free to point it out :)

Thanks in advance for taking the time to answer to this question!!

**Comment by gandhirajan** [comment]
@legendactivated hi, it picks up model.jar from temporal resource module itself. You can open the source code to cross check the same.

**Comment by legendactivated** [comment]
Ok sounds good. Thanks for the reply, @gandhirajan!
