### ISSUE TITLE
Another question

### ISSUE THREAD

**Issue by legendactivated** [GoTeamEpsilon/ctakes-rest-service#59]
Hi @gandhirajan,

Just wanted to see if you were able to merge changes from Tim Miller in  https://issues.apache.org/jira/browse/CTAKES-529?

Thanks!

**Comment by gandhirajan** [comment]
Hi @legendactivated , ctakes rest module is already checked-in into ctakes svn repo. Tim Miller's merge is on top of our code. You can simply pull the latest changes from https://svn.apache.org/repos/asf/ctakes/trunk/ctakes-web-rest/
