### ISSUE TITLE
Inconsistent working of API

### ISSUE THREAD

**Issue by singhmousam** [GoTeamEpsilon/ctakes-rest-service#60]

**Comment by singhmousam** [comment]
Hello,
I successfully installed the REST API on my desktop and the issue I am facing is that, I always need to restart my system to use the api for some duration. On restarting the system the api works for some time and then again dies off.
I tried but wasn't able to figure the issue. Is anybody else facing the same issue. Let me know if there are any solutions to it. And also to add into this the use of api leads to starting of numerous threads in the background which may also be a sign of ill functioning.
![capture1](https://user-images.githubusercontent.com/31251993/54032654-4baed080-41d8-11e9-800e-2f2dc3110db4.PNG)
![capture](https://user-images.githubusercontent.com/31251993/54032656-4c476700-41d8-11e9-8a8f-9be344a2b78c.PNG)

**Comment by MatthewVita** [comment]
Hi. One of the Team Epsilon folks here. I have been away from open source for many months due to health issues.

You may be interested in reviewing the brand new README, which may lead you to a smoother install. Please let me know if you have any difficulties navigating it.
