### ISSUE TITLE
index.css:1 Failed to load resource: the server responded with a status of 404 ()

### ISSUE THREAD

**Issue by singhmousam** [GoTeamEpsilon/ctakes-rest-service#61]
After a successful startup the api works for a single session only. On closing and restarting it the stops functioning and on looking for it's solution I found that the index.jsp has been given the reference of index.css from css directory which it is unable to find. 
It's solution maybe to put the required file at it's place, but the file is not provided in the repository.
Please look into the issue.

**Comment by MatthewVita** [comment]
Hi. One of the Team Epsilon folks here. I have been away from open source for many months due to health issues.

You may be interested in reviewing the brand new README, which may lead you to a smoother install. Please let me know if you have any difficulties navigating it.
