### ISSUE TITLE
Could not resolve dependencies for project

### ISSUE THREAD

**Issue by nitindesaiiks** [GoTeamEpsilon/ctakes-rest-service#66]
I am following README of the project but getting below ERROR:

[ERROR] Failed to execute goal on project ctakes-distribution: Could not resolve dependencies for project org.apache.ctakes:ctakes-distribution:pom:4.0.1-SNAPSHOT: The following artifacts could not be resolved: org.apache.ctakes:ctakes-type-system:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-core:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-core-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-utils:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-context-tokenizer:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-dictionary-lookup:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-dictionary-lookup-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-dictionary-lookup-fast:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-dictionary-lookup-fast-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-examples:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-examples-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-preprocessor:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-lvg:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-lvg-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-chunker:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-chunker-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-ne-contexts:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-ne-contexts-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-pos-tagger:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-pos-tagger-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-assertion:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-assertion-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-dependency-parser:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-dependency-parser-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-clinical-pipeline:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-clinical-pipeline-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-constituency-parser:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-constituency-parser-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-coreference:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-coreference-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-drug-ner:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-drug-ner-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-relation-extractor:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-relation-extractor-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-side-effect:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-side-effect-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-smoking-status:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-smoking-status-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-temporal:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-temporal-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-ytex:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-ytex-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-ytex-uima:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-ytex-web:jar:classes:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-gui:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-gui-res:jar:4.0.1-SNAPSHOT, org.apache.ctakes:ctakes-fhir:jar:4.0.1-SNAPSHOT: Could not transfer artifact org.apache.ctakes:ctakes-type-system:jar:4.0.1-20190719.123203-123 from/to apache.snapshots (http://repository.apache.org/snapshots): GET request of: org/apache/ctakes/ctakes-type-system/4.0.1-SNAPSHOT/ctakes-type-system-4.0.1-20190719.123203-123.jar from apache.snapshots failed: Premature end of Content-Length delimited message body (expected: 426524; received: 2375 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

I am not that much familiar with how maven builds works internally. Thanks for any help.

**Comment by MatthewVita** [comment]
Hi @nitindesaiiks,

There may be a couple of ways to approach this, but I would say you're having this problem is because of an overencumbered server/computer.

Basically, the warning states `Premature end of Content-Length delimited message body (expected: 426524; received: 2375`. That's like ~2% of the total data needed to be received.

Can you verify you have adequate CPU/RAM/etc resources on the cTAKES server/computer?

-m

**Comment by nitindesaiiks** [comment]
It might be because of internet restrictions of my org. I downloaded the dependencies and placed them in repository and that worked for me. Thank you : )
