### ISSUE TITLE
If I just clone the ctakes-rest-service ignore the code-base-step

### ISSUE THREAD

**Issue by ileadall42** [GoTeamEpsilon/ctakes-rest-service#68]
I mean  if I just `mvn install` this project but ignore the svn project.
Ignore the following step ,what will happen ?
```
mkdir ctakes-codebase-area
cd ctakes-codebase-area
svn export 'https://svn.apache.org/repos/asf/ctakes/trunk'
cd trunk/ctakes-distribution
mvn install -Dmaven.test.skip=true
cd ../ctakes-assertion-zoner
mvn install -Dmaven.test.skip=true
cd ../../../ctakes-web-rest
mvn install
```

**Comment by MatthewVita** [comment]
Not sure I follow - the REST service is not very useful without a cTAKES backing (from svn).

Maybe I'm missing the question - can you point out concerns? Thanks!
